@include('financial-administrative-directorate.layout.head')
@include('financial-administrative-directorate.payroll-management.layout.sidebar')
@include('financial-administrative-directorate.layout.header')
@yield('contents')
@include('financial-administrative-directorate.layout.footer')
