@include('financial-administrative-directorate.layout.head')
@include('financial-administrative-directorate.save-and-care.layout.sidebar')
@include('financial-administrative-directorate.layout.header')
@yield('contents')
@include('financial-administrative-directorate.layout.footer')
